// INTRODUÇÃO AO ARRAYS
// ADD NOVOS ELEMENTOS
// ENCONTRAR ELEMENTOS
// REMOVER ELEMENTOS
// DIVIDIR ELEMENTOS
// DIVIDIR ARRAYS
// COMBINAR ARRAYS



// ADD NOVOS ELEMENTOS
const numeros = [1,2,3];

// ADD ELEMENTO NO INÍCIO DO ARRAY
numeros.unshift(0)
console.log(numeros)